# Generated by Django 2.2 on 2021-02-18 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batchapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='num',
            new_name='codes',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='user',
        ),
    ]
